name: Manage tag
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  tag:
    name: Manage tag
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4
    -
      uses: haya14busa/action-update-semver@v1
      with:
        major_version_tag_only: true
